FROM mono:3.10

ENV  HOME /root

RUN  apt-get -qq update && apt-get -qqy install curl unzip build-essential procps && \
     apt-get clean autoclean && apt-get autoremove -y && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN  curl -s https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && \
     bash -c "source /root/.kre/kvm/kvm.sh && \
     kvm upgrade && \
     kvm alias default | xargs -i ln -s /root/.kre/packages/{} /root/.kre/packages/default"

ENV  PATH $PATH:/root/.kre/packages/default/bin

# source:
# http://msopentech.com/blog/2014/11/07/creating-asp-net-vnext-docker-container-using-mono-2/