FROM            polykube/aspvnextbase
MAINTAINER      Cole Mickens <cole.mickens@gmail.com>

# everything after this is specific to polykube

ADD             . /root/polykube/

RUN             bash -c "source /root/.kre/kvm/kvm.sh && cd /root/polykube/ && kpm --verbose restore"

WORKDIR         /root/polykube/src/Polykube.vNextApi/
CMD             /root/polykube/src/Polykube.vNextApi/start_k_daemon.sh

EXPOSE 8000