FROM    ubuntu:latest
ENV     HOME /root

RUN 
RUN     apt-get -qq update && apt-get -qqy install curl && \
        curl http://download.mono-project.com/repo/xamarin.gpg > /tmp/xamarin.gpg && \
        apt-key add /tmp/xamarin.gpg && \
        echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list && \
        apt-get -qq update && apt-get -qqy install unzip build-essential mono-complete && \
        apt-get clean autoclean && apt-get autoremove -y && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN     mozroots --import --sync

RUN     curl https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh > /root/kvminstall.sh &&\
        sh /root/kvminstall.sh && \
        bash -c "source ~/.kre/kvm/kvm.sh && kvm upgrade"
